name: "Deploy"
description: "Run terraform apply"
inputs:
  environment:
    description: "Target environment"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - run: terraform init
      shell: bash
      working-directory: terraform/environments/${{ inputs.environment }}
    - run: terraform apply -auto-approve -input=False 
      shell: bash
      working-directory: terraform
