name: Deploy
on:
  workflow_call:
jobs:
  staging:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/deploy
  production:
    needs: staging
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/deploy
