name: Deploy
on:
  workflow_run:
    workflows: ['Publish', 'Functions']
    branches: [main]
    types: 
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      # TODO: create tag for current version.