name: Deploy
on:
  workflow_call:
jobs:
  staging:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "{EARS_VERSION}=$(cat terraform/VERSION)" >> $GITHUB_ENV
      - run: git tag ${{ env.EARS_VERSION }}-dev.${{ github.run_id }}
      - run: git push origin ${{ env.EARS_VERSION }}
  production:
    needs: staging
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "{EARS_VERSION}=$(cat terraform/VERSION)" >> $GITHUB_ENV
      - run: git tag ${{ env.EARS_VERSION }}
      - run: git push origin ${{ env.EARS_VERSION }}
