name: Functions
on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        functions:
          - beatport
          - deezer
          - slack
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Cache poetry
        id: poetry
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Setup poetry
        run: poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: |
          poetry install
          sed -i 's/ears.*//g' functions/${{ matrix.functions }}/requirements.txt
          pip install -r functions/${{ matrix.functions }}/requirements.txt
        if: steps.requirements.outputs.cache-hit != 'true'
      - name: Run black
        run: |
          poetry run black functions/${{ matrix.functions }} --check
      - name: Run isort
        run: |
          poetry run isort functions/${{ matrix.functions }} --check
      - name: Run mypy
        run: |
          poetry run mypy --strict functions/${{ matrix.functions }}