name: Main
on:
  push:
    branches:
      - main
jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  publish:
    if: startsWith(github.event.head_commit.message, "🔖")
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Set up poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - name: Setup PyPi credentials
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish to PyPi
        run: poetry publish
  deploy:
    if: startsWith(github.event.head_commit.message, "🔖")
    needs: Publish
    uses: ./.github/workflows/deploy.yaml
