name: Publish
on:
  workflow_run:
    workflows: ['Core']
    branches: [main]
    types: 
      - completed
jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Set up poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - name: Setup PyPi credentials
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish to PyPi
        run: poetry publish
