name: Publish
on:
  push:
    branches:
      - main
jobs:
  test_package:
    uses: .github/workflows/tests/core.yaml
  publish_pypi:
    needs: test_package
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Set up poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - name: Setup PyPi credentials
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish to PyPi
        run: poetry publish
