name: Tests
on:
  pull_request:
    branches:    
      - main
  workflow_call:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/lint
        with:
          targets: "ears tests"
      - name: Run pytest
        run: poetry run pytest tests
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/staging
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate -no-color
      - run: terraform plan -no-color -input=false
  functions:
    needs: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        functions:
          - beatport
          - deezer
          - slack
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Install function dependencies
        run: |
          sed -i 's/ears.*//g' functions/${{ matrix.functions }}/requirements.txt
          pip install -r functions/${{ matrix.functions }}/requirements.txt
      - uses: ./.github/actions/lint
        with:
          targets: functions/${{ matrix.functions }}