name: Tests
on:
  pull_request:
    branches:    
      - main
jobs:
  test_package:
    uses: .github/workflows/tests/core.yaml
  test_cloud_functions:
    needs: test_package
    uses: .github/workflows/tests/functions.yaml